FROM ubuntu:18.04
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
RUN apt-get install -y tzdata

RUN apt-get install -y sqlite3

RUN apt-get install -y pwgen
RUN apt-get install -y git-core
RUN apt-get install -y trac
# trac has native support for git since version 1.0
# RUN apt-get install -y trac-git
RUN apt-get install -y trac-accountmanager
RUN apt-get install -y trac-customfieldadmin
RUN apt-get install -y trac-xmlrpc
RUN apt-get install -y trac-wikiprint
RUN apt-get install -y trac-wysiwyg
RUN apt-get install -y trac-mastertickets
RUN apt-get install -y trac-tags
RUN apt-get install -y trac-diavisview
RUN apt-get install -y trac-announcer
# trac has native support for batchmodify since version 1.0.1
# RUN apt-get install -y trac-batchmodify
RUN apt-get install -y trac-graphviz
RUN apt-get install -y trac-navadd
RUN apt-get install -y python-flup
# required by TracLDAPAuth
RUN apt-get install -y python-ldap
# needed to install TracLDAPAuth
RUN apt-get update
RUN apt-get install -y python-pip
# make editing configuration files a bit easier
RUN apt-get install -y nano
RUN pip install TracLDAPAuth

ADD setup_trac_config.sh /.setup_trac_config.sh
ADD setup_trac.sh /.setup_trac.sh
ADD run.sh /run.sh
ADD trac_logo.png /var/www/trac_logo.png

ADD set_trac_user_password.py /usr/local/bin/
RUN chmod 755 /usr/local/bin/set_trac_user_password.py

# hack our timezone; should not be needed though
RUN ln -fs /usr/share/zoneinfo/Pacific/Auckland /etc/localtime
RUN dpkg-reconfigure -f noninteractive tzdata

# here we keep our backups
RUN mkdir /backup
# here we restore from
RUN mkdir /restore

EXPOSE 80
CMD ["/run.sh"]
